CREATE TABLE IF NOT EXISTS account (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password BYTEA NOT NULL,
    salt BYTEA NOT NULL,
    fullname VARCHAR(256) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    token VARCHAR(128),
    tokenupdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status BOOLEAN,
    createddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);